### YamlMime:UniversalReference
items:
  - uid: Api.Js.InPage.Environment
    name: Environment
    fullName: Environment
    children:
      - Api.Js.InPage.Environment.api
      - Api.Js.InPage.Environment.load
      - Api.Js.InPage.Environment.page
      - Api.Js.InPage.Environment.platform
      - Api.Js.InPage.Environment.ready
      - Api.Js.InPage.Environment.rvt
      - Api.Js.InPage.Environment.rvtHeader
      - Api.Js.InPage.Environment.source
    langs:
      - typeScript
    type: class
    summary: >-
      Provides environment information to $2sxc - usually page-id, api-root and
      stuff like that
    extends:
      name: Api.Js.InPage.HasLog
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.api
    name: api()
    children: []
    type: method
    langs:
      - typeScript
    summary: The API endpoint url from the environment
    syntax:
      content: function api()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.load
    name: 'load(EnvironmentSpecs, string)'
    children: []
    type: method
    langs:
      - typeScript
    summary: >-
      Manually load a new EnvironmentSpecs in cases where the page cannot
      provide them.

      This is only used in scenarios outside of Dnn / Oqtane, you will usually
      not need this.
    syntax:
      content: 'function load(newJsInfo: EnvironmentSpecs, source?: string)'
      parameters:
        - id: newJsInfo
          type:
            - Api.Js.InPage.EnvironmentSpecs
          description: |
            new info to load
        - id: source
          type:
            - string
          description: ''
          optional: true
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.page
    name: page()
    children: []
    type: method
    langs:
      - typeScript
    summary: The current page ID - often needed in API calls
    syntax:
      content: function page()
      parameters: []
      return:
        type:
          - number
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.platform
    name: platform()
    children: []
    type: method
    langs:
      - typeScript
    summary: >-
      The platform code like 'oqt' or 'dnn' in case the JS needs to know the
      difference
    syntax:
      content: function platform()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.ready
    name: ready
    fullName: ready
    children: []
    langs:
      - typeScript
    type: property
    summary: ''
    syntax:
      content: 'public ready: boolean = false'
      return:
        type:
          - boolean
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.rvt
    name: rvt()
    children: []
    type: method
    langs:
      - typeScript
    summary: The request-verification token for internal WebAPI calls
    syntax:
      content: function rvt()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.rvtHeader
    name: rvtHeader()
    children: []
    type: method
    langs:
      - typeScript
    summary: The request verification token header name for internal WebAPI calls
    syntax:
      content: function rvtHeader()
      parameters: []
      return:
        type:
          - string
        description: ''
    package: Api.Js.InPage
  - uid: Api.Js.InPage.Environment.source
    name: source
    fullName: source
    children: []
    langs:
      - typeScript
    type: property
    summary: ''
    syntax:
      content: 'public source: string = ""'
      return:
        type:
          - string
        description: ''
    package: Api.Js.InPage
references:
  - uid: Api.Js.InPage.HasLog
    name: HasLog
    spec.typeScript:
      - name: HasLog
        fullName: HasLog
        uid: Api.Js.InPage.HasLog
  - uid: Api.Js.InPage.EnvironmentSpecs
    name: EnvironmentSpecs
    spec.typeScript:
      - name: EnvironmentSpecs
        fullName: EnvironmentSpecs
        uid: Api.Js.InPage.EnvironmentSpecs
